### ISSUE TITLE
Add support for gatech 2 factor login

### ISSUE THREAD

**Issue by jgkamat** [LUGatGT/t2#1]
I think this is causing this error for me so I can't login:

```
[jay@gilly t2]$ t2 list 
Traceback (most recent call last):
  File "/sbin/t2", line 59, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/sbin/t2", line 31, in list
    courses = t2.list_courses()
  File "/usr/lib/python3.5/site-packages/t2/__init__.py", line 60, in list_courses
    courses = [link.get_attribute('title') for link in driver.find_element_by_id("siteLinkList").find_elements_by_css_selector('li > a')]
  File "/usr/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with id 'siteLinkList'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"93","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:57615","User-Agent":"Python-urllib/3.5"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"id\", \"sessionId\": \"da3db710-8be8-11e6-8c6c-e3438452fe4a\", \"value\": \"siteLinkList\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/da3db710-8be8-11e6-8c6c-e3438452fe4a/element"}}
Screenshot: available via screen
```

I'm not sure how to get the screenshot to debug, where is this placed?

**Comment by richardscollin** [comment]
So currently I don't have it set up to generate a screenshot when it crashes. I should add that. Possibly also a crash handler that will log these errors in a text file for later retrival.

I also think that implementing 2 factor will be a waste of effort until I have the login credentials cached. Otherwise you'd have to do two factor auth for every command run.
